[package]
name = "riot-rs-timers"
version = "0.1.0"
authors = ["Kaspar Schleiser <kaspar@schleiser.de>"]
edition = "2021"
license = "Apache-2.0"

[lints]
workspace = true

[dependencies]
riot-rs = { path = "../riot-rs" }
