[package]
name = "riot-rs-core"
version = "0.1.0"
authors = ["Kaspar Schleiser <kaspar@schleiser.de>"]
edition = "2021"

links = "riot-rs-core"

[dependencies]
critical-section.workspace = true
ref-cast = "1.0"
riot-rs-threads = { path = "../riot-rs-threads" }

ringbuffer = { path = "../lib/ringbuffer" }

[build-dependencies]
cbindgen = "0.26.*"

[dev-dependencies]
riot-rs-boards = { path = "../riot-rs-boards" }
riot-rs-rt = { path = "../riot-rs-rt" }
