[package]
name = "riot-rs-chips"
version = "0.1.0"
authors = ["Kaspar Schleiser <kaspar@schleiser.de>"]
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stm32f4xx = { optional = true, path = "stm32f4xx" }

[features]
stm32f401 = ["stm32f4xx/stm32f401"]
