[package]
name = "riot-rs-rt"
version = "0.1.0"
authors = ["Kaspar Schleiser <kaspar@schleiser.de>"]
edition = "2021"

[lints]
workspace = true

[dependencies]
cfg-if.workspace = true
linkme.workspace = true
riot-rs-debug.workspace = true
riot-rs-threads = { path = "../riot-rs-threads", optional = true }
riot-rs-utils = { path = "../riot-rs-utils" }

[target.'cfg(context = "cortex-m")'.dependencies]
cortex-m = { workspace = true, features = ["critical-section-single-core"] }
cortex-m-rt = { workspace = true }
portable-atomic = { version = "1.6.0", features = ["critical-section"] }

[features]
#default = ["threading"]
threading = ["dep:riot-rs-threads"]
debug-console = ["riot-rs-debug/debug-console"]
silent-panic = []
_panic-handler = []

[dev-dependencies]
riot-rs-boards = { path = "../riot-rs-boards" }
