[package]
name = "riot-rs-rp"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
embassy-net-driver-channel = { workspace = true, optional = true }
embassy-rp = { workspace = true, default-features = false, features = [
  "rt",
  "time-driver",
  "unstable-pac",
  # "unstable-traits",
] }
riot-rs-debug = { workspace = true }
riot-rs-shared-types = { workspace = true }
riot-rs-utils = { workspace = true }
static_cell = { workspace = true, optional = true }

# rpi-pico-w cyw43
cyw43 = { version = "0.1.0", features = ["firmware-logs"], optional = true }
cyw43-pio = { version = "0.1.0", features = ["overclock"], optional = true }

[target.'cfg(context = "cortex-m")'.dependencies]
embassy-executor = { workspace = true, default-features = false, features = [
  "arch-cortex-m",
] }

[features]
## Enables GPIO interrupt support.
external-interrupts = ["riot-rs-shared-types/external-interrupts"]

## Enables USB support.
usb = []

## Enables defmt support.
defmt = ["embassy-rp/defmt"]

## Enables Wi-Fi support.
wifi = []

## Enables support for the CYW43 Wi-Fi chip.
wifi-cyw43 = [
  "dep:cyw43",
  "dep:cyw43-pio",
  "dep:embassy-net-driver-channel",
  "dep:static_cell",
  "wifi",
]

## Enables the interrupt executor.
executor-interrupt = ["embassy-executor/executor-interrupt"]
