[package]
name = "riot-rs-utils"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
const_panic = { workspace = true }
# env utils
konst = { workspace = true, features = ["parsing"] }
