[package]
name = "nrf52"
version = "0.1.0"
authors = ["Kaspar Schleiser <kaspar@schleiser.de>"]
edition = "2021"

[dependencies]
nrf52832-pac = { version = "0.12.2", default-features = false, features = [
  "rt",
], optional = true }
nrf52840-pac = { version = "0.12.2", default-features = false, features = [
  "rt",
], optional = true }
riot-rs-rt = { path = "../../riot-rs-rt", features = ["rtt-target"] }

[features]
nrf52832 = ["dep:nrf52832-pac"]
nrf52840 = ["dep:nrf52840-pac"]

[build-dependencies]
ld-memory = { workspace = true, features = ["build-rs"] }
