[package]
name = "riot-rs-shared-types"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
embedded-hal = { workspace = true }

[features]
## Enables GPIO interrupt support.
external-interrupts = []
